[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.14.0"]
build-backend = "hatchling.build"

[project]
name = "lidar-projekti"
dynamic = ["version"]
description = ""
authors = [{ name = "Lari Liuhamo", email = "diapolo10@gitlab.tamk.cloud" }]
requires-python = ">=3.11"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[dependency-groups]
dev = ["Sphinx>=9.0.4", "breathe>=4.36.0"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { git = { commit = true, tags = true } },
]
constraint-dependencies = ["pygments>=2.20.0"]
package = false

[tool.uv-dynamic-versioning]
bump = true
fallback-version = "0.0.0"
style = "pep440"
vcs = "git"
